export const DEFAULT_UI = {
  tab_read: 'Loe',
  tab_review: 'Korda',
  tab_phrases: 'Väljendid',
  generate: 'Loo uus tekst',
  from_cache: 'Kuva mingit varasemat',
  generating: 'Loon teksti...',
  cards: 'Kaardid',
  fill_blank_mode: 'Lünktäitmine',
  words_due: 'sõna täna korrata',
  words_upcoming: 'sõna tuleb hiljem',
  start_today: 'Alusta tänastega',
  review_all: 'Korda kõiki',
  all_done: 'Täna on kõik tehtud!',
  words_coming_next: 'sõna tuleb järgmistel päevadel',
  session_done: 'Sessioon lõppenud!',
  easy: 'Lihtne',
  ok: 'Okei',
  hard: 'Raske',
  back: 'Tagasi',
  loading_examples: 'Laen näitelauseid...',
  fill_blank_title: 'Täida lünk',
  next: 'Järgmine →',
  correct: '✓ Õige!',
  wrong_prefix: '✗ Õige vastus:',
  exercise_error: 'Viga ülesande genereerimisel',
  try_again: 'Proovi uuesti',
  generate_phrases: 'Genereeri väljendid',
  review_btn: 'Korda',
  tap_for_explanation: 'vajuta selgituse nägemiseks',
  word_for_word: 'sõna-sõnalt',
  save_phrases_hint: 'Salvesta väljendeid tärniga',
  show: 'Näita',
  to_start: 'Algusesse ↺',
  translating: 'Tõlgin...',
  word_saved: '★ Salvestatud',
  word_save: '☆ Salvesta',
  add_words_hint: 'Lisa sõnu Loe vaates ⭐ nupuga.',
  no_saved_phrases: 'Salvesta väljendeid tärniga',
};

export const LANGUAGES = [
  { label: 'afrikaans', value: 'Afrikaans' },
  { label: 'araabia', value: 'Arabic' },
  { label: 'eesti', value: 'Estonian' },
  { label: 'heebrea', value: 'Hebrew' },
  { label: 'hiina', value: 'Chinese' },
  { label: 'hindi', value: 'Hindi' },
  { label: 'hispaania', value: 'Spanish' },
  { label: 'hollandi', value: 'Dutch' },
  { label: 'horvaadi', value: 'Croatian' },
  { label: 'indoneesia', value: 'Indonesian' },
  { label: 'inglise', value: 'English' },
  { label: 'itaalia', value: 'Italian' },
  { label: 'jaapani', value: 'Japanese' },
  { label: 'katalaani', value: 'Catalan' },
  { label: 'korea', value: 'Korean' },
  { label: 'kreeka', value: 'Greek' },
  { label: 'bulgaaria', value: 'Bulgarian' },
  { label: 'läti', value: 'Latvian' },
  { label: 'leedu', value: 'Lithuanian' },
  { label: 'norra', value: 'Norwegian' },
  { label: 'poola', value: 'Polish' },
  { label: 'portugali', value: 'Portuguese' },
  { label: 'prantsuse', value: 'French' },
  { label: 'rootsi', value: 'Swedish' },
  { label: 'rumeenia', value: 'Romanian' },
  { label: 'saksa', value: 'German' },
  { label: 'serbia', value: 'Serbian' },
  { label: 'slovaki', value: 'Slovak' },
  { label: 'soome', value: 'Finnish' },
  { label: 'tai', value: 'Thai' },
  { label: 'taani', value: 'Danish' },
  { label: 'tšehhi', value: 'Czech' },
  { label: 'türgi', value: 'Turkish' },
  { label: 'ukraina', value: 'Ukrainian' },
  { label: 'ungari', value: 'Hungarian' },
  { label: 'vene', value: 'Russian' },
  { label: 'vietnami', value: 'Vietnamese' },
];
