export const DEFAULT_UI = {
  tab_read: 'Loe',
  tab_review: 'Korda',
  tab_phrases: 'Väljendid',
  generate: 'Genereeri',
  from_cache: 'Vahemälust',
  generating: 'Genereerin...',
  cards: 'Kaardid',
  fill_blank_mode: 'Lünktäitmine',
  words_due: 'sõna täna korrata',
  words_upcoming: 'sõna tuleb hiljem',
  start_today: 'Alusta tänastega',
  review_all: 'Korda kõiki',
  all_done: 'Täna on kõik tehtud!',
  words_coming_next: 'sõna tuleb järgmistel päevadel',
  session_done: 'Sessioon lõppenud!',
  easy: 'Lihtne',
  ok: 'Okei',
  hard: 'Raske',
  back: 'Tagasi',
  loading_examples: 'Laen näitelauseid...',
  fill_blank_title: 'Täida lünk',
  next: 'Järgmine →',
  correct: '✓ Õige!',
  wrong_prefix: '✗ Õige vastus:',
  exercise_error: 'Viga ülesande genereerimisel',
  try_again: 'Proovi uuesti',
  generate_phrases: 'Genereeri väljendid',
  review_btn: 'Korda',
  tap_for_explanation: 'vajuta selgituse nägemiseks',
  word_for_word: 'sõna-sõnalt',
  save_phrases_hint: 'Salvesta väljendeid tärniga',
  show: 'Näita',
  to_start: 'Algusesse ↺',
  translating: 'Tõlgin...',
  word_saved: '★ Salvestatud',
  word_save: '☆ Salvesta',
  add_words_hint: 'Lisa sõnu Loe vaates ⭐ nupuga.',
  no_saved_phrases: 'Salvesta väljendeid tärniga',
};

export const LANGUAGES = [
  { label: 'Afrikaans', value: 'Afrikaans' },
  { label: 'Araabia', value: 'Arabic' },
  { label: 'Bulgaaria', value: 'Bulgarian' },
  { label: 'Katalaani', value: 'Catalan' },
  { label: 'Hiina', value: 'Chinese' },
  { label: 'Horvaadi', value: 'Croatian' },
  { label: 'Tšehhi', value: 'Czech' },
  { label: 'Taani', value: 'Danish' },
  { label: 'Hollandi', value: 'Dutch' },
  { label: 'Inglise', value: 'English' },
  { label: 'Eesti', value: 'Estonian' },
  { label: 'Soome', value: 'Finnish' },
  { label: 'Prantsuse', value: 'French' },
  { label: 'Saksa', value: 'German' },
  { label: 'Kreeka', value: 'Greek' },
  { label: 'Heebrea', value: 'Hebrew' },
  { label: 'Hindi', value: 'Hindi' },
  { label: 'Ungari', value: 'Hungarian' },
  { label: 'Indoneesia', value: 'Indonesian' },
  { label: 'Itaalia', value: 'Italian' },
  { label: 'Jaapani', value: 'Japanese' },
  { label: 'Korea', value: 'Korean' },
  { label: 'Läti', value: 'Latvian' },
  { label: 'Leedu', value: 'Lithuanian' },
  { label: 'Norra', value: 'Norwegian' },
  { label: 'Poola', value: 'Polish' },
  { label: 'Portugali', value: 'Portuguese' },
  { label: 'Rumeenia', value: 'Romanian' },
  { label: 'Vene', value: 'Russian' },
  { label: 'Serbia', value: 'Serbian' },
  { label: 'Slovaki', value: 'Slovak' },
  { label: 'Hispaania', value: 'Spanish' },
  { label: 'Rootsi', value: 'Swedish' },
  { label: 'Tai', value: 'Thai' },
  { label: 'Türgi', value: 'Turkish' },
  { label: 'Ukraina', value: 'Ukrainian' },
  { label: 'Vietnami', value: 'Vietnamese' },
];
